import { Provider } from "react-redux";
import { store } from "@/Store/store";
import "./globals.css";
import ReduxProvider from "./ReduxProvider";
import ToastProvider from "@/components/ToastProvider";

export const metadata = {
  title: "ClothNet",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="true"
>
        <ReduxProvider >
        <ToastProvider/>
        {children}</ReduxProvider>
      </body>
    </html>
  );
}
